services:
  pg-db:
    image: postgres:14
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-laravel}'
      POSTGRES_USER: '${DB_USERNAME:-laravel}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pg-db:/var/lib/postgresql/data'
    networks:
      - laravel_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-laravel}", "-U", "${DB_USERNAME:-laravel}" ]
  # mailhog:
  #   image: 'mailhog/mailhog:latest'
  #   ports:
  #     - '${FORWARD_MAILHOG_PORT:-1026}:1026'
  #     - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8026'
  #   networks:
  #     - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  pg-db:
    driver: local
